<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/file_ref.proto

namespace Io\Altessa\Type\V1\FileRef;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Technical descriptors of the referenced file. Producers SHOULD populate
 * every field they know; consumers MUST tolerate missing values
 * (e.g. legacy records, third-party uploads without inspection).
 *
 * Generated from protobuf message <code>io.altessa.type.v1.FileRef.Metadata</code>
 */
class Metadata extends \Google\Protobuf\Internal\Message
{
    /**
     * IANA media type of the file content (RFC 6838), e.g. "image/png",
     * "application/pdf", "text/plain".
     *
     * Generated from protobuf field <code>string mime_type = 1 [json_name = "mimeType"];</code>
     */
    protected $mime_type = '';
    /**
     * Size of the file in bytes. Negative values are not meaningful.
     *
     * Generated from protobuf field <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
     */
    protected $size_bytes = 0;
    /**
     * Original filename including extension, e.g. "report.pdf",
     * "photo.jpg". Not guaranteed to be unique within the storage backend.
     *
     * Generated from protobuf field <code>string filename = 3 [json_name = "filename"];</code>
     */
    protected $filename = '';
    /**
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     *
     * Generated from protobuf field <code>map<string, string> custom = 4 [json_name = "custom"];</code>
     */
    private $custom;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $mime_type
     *           IANA media type of the file content (RFC 6838), e.g. "image/png",
     *           "application/pdf", "text/plain".
     *     @type int|string $size_bytes
     *           Size of the file in bytes. Negative values are not meaningful.
     *     @type string $filename
     *           Original filename including extension, e.g. "report.pdf",
     *           "photo.jpg". Not guaranteed to be unique within the storage backend.
     *     @type array|\Google\Protobuf\Internal\MapField $custom
     *           Free-form key/value pairs for caller-defined attributes (checksums,
     *           alt text, source system, …).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Altessa\Type\V1\FileRef::initOnce();
        parent::__construct($data);
    }

    /**
     * IANA media type of the file content (RFC 6838), e.g. "image/png",
     * "application/pdf", "text/plain".
     *
     * Generated from protobuf field <code>string mime_type = 1 [json_name = "mimeType"];</code>
     * @return string
     */
    public function getMimeType()
    {
        return $this->mime_type;
    }

    /**
     * IANA media type of the file content (RFC 6838), e.g. "image/png",
     * "application/pdf", "text/plain".
     *
     * Generated from protobuf field <code>string mime_type = 1 [json_name = "mimeType"];</code>
     * @param string $var
     * @return $this
     */
    public function setMimeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->mime_type = $var;

        return $this;
    }

    /**
     * Size of the file in bytes. Negative values are not meaningful.
     *
     * Generated from protobuf field <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
     * @return int|string
     */
    public function getSizeBytes()
    {
        return $this->size_bytes;
    }

    /**
     * Size of the file in bytes. Negative values are not meaningful.
     *
     * Generated from protobuf field <code>int64 size_bytes = 2 [json_name = "sizeBytes"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSizeBytes($var)
    {
        GPBUtil::checkInt64($var);
        $this->size_bytes = $var;

        return $this;
    }

    /**
     * Original filename including extension, e.g. "report.pdf",
     * "photo.jpg". Not guaranteed to be unique within the storage backend.
     *
     * Generated from protobuf field <code>string filename = 3 [json_name = "filename"];</code>
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Original filename including extension, e.g. "report.pdf",
     * "photo.jpg". Not guaranteed to be unique within the storage backend.
     *
     * Generated from protobuf field <code>string filename = 3 [json_name = "filename"];</code>
     * @param string $var
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->filename = $var;

        return $this;
    }

    /**
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     *
     * Generated from protobuf field <code>map<string, string> custom = 4 [json_name = "custom"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCustom()
    {
        return $this->custom;
    }

    /**
     * Free-form key/value pairs for caller-defined attributes (checksums,
     * alt text, source system, …).
     *
     * Generated from protobuf field <code>map<string, string> custom = 4 [json_name = "custom"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCustom($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->custom = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Metadata::class, \Io\Altessa\Type\V1\FileRef_Metadata::class);

