<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: badrequest/v1/badrequest.proto

namespace GPBMetadata\Badrequest\V1;

class Badrequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE1\x07\x0A\x1Ebadrequest/v1/badrequest.proto\x12\x18io.altessa.badrequest.v1\x1A google/protobuf/descriptor.proto\"a\x0A\x0ABadRequest\x12S\x0A\x10field_violations\x18\x01 \x03(\x0B2(.io.altessa.badrequest.v1.FieldViolationR\x0FfieldViolations\"\xBF\x01\x0A\x0EFieldViolation\x12\x1D\x0A\x0Afield_path\x18\x01 \x01(\x09R\x09fieldPath\x12\x18\x0A\x07message\x18\x02 \x01(\x09R\x07message\x12\x12\x0A\x04code\x18\x03 \x01(\x09R\x04code\x12`\x0A\x15field_path_components\x18\x04 \x03(\x0B2,.io.altessa.badrequest.v1.FieldPathComponentR\x13fieldPathComponents\"\x81\x04\x0A\x12FieldPathComponent\x12\x16\x0A\x06number\x18\x01 \x01(\x05R\x06number\x12\x12\x0A\x04name\x18\x02 \x01(\x09R\x04name\x12>\x0A\x04type\x18\x03 \x01(\x0E2*.google.protobuf.FieldDescriptorProto.TypeR\x04type\x12L\x0A\x0Cmap_key_type\x18\x04 \x01(\x0E2*.google.protobuf.FieldDescriptorProto.TypeR\x0AmapKeyType\x12P\x0A\x0Emap_value_type\x18\x05 \x01(\x0E2*.google.protobuf.FieldDescriptorProto.TypeR\x0CmapValueType\x12\x1F\x0A\x0Bis_repeated\x18\x06 \x01(\x08R\x0AisRepeated\x12%\x0A\x0Erepeated_index\x18\x07 \x01(\x04R\x0DrepeatedIndex\x12\x16\x0A\x05index\x18\x08 \x01(\x04H\x00R\x05index\x12\x1B\x0A\x08bool_key\x18\x09 \x01(\x08H\x00R\x07boolKey\x12\x19\x0A\x07int_key\x18\x0A \x01(\x03H\x00R\x06intKey\x12\x1B\x0A\x08uint_key\x18\x0B \x01(\x04H\x00R\x07uintKey\x12\x1F\x0A\x0Astring_key\x18\x0C \x01(\x09H\x00R\x09stringKeyB\x09\x0A\x07map_keyBZ\x0A\x18io.altessa.badrequest.v1P\x01Z<github.com/altessa-s/proto-gen-go/badrequest/v1;badrequestv1"
        , true);

        static::$is_initialized = true;
    }
}

