<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

namespace Io\Altessa\Serviceinfo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for the `GetServiceInfo` method. `ServiceInfo` is a per-connection
 * singleton — the instance answering the call — so there is no `name` to
 * address. The message is intentionally empty for now and exists (instead
 * of `google.protobuf.Empty`) so read options such as a
 * `google.protobuf.FieldMask` can be added later without changing the RPC
 * signature.
 *
 * Generated from protobuf message <code>io.altessa.serviceinfo.v1.GetServiceInfoRequest</code>
 */
class GetServiceInfoRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Altessa\Serviceinfo\V1\ServiceinfoService::initOnce();
        parent::__construct($data);
    }

}

