<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

namespace Io\Altessa\Serviceinfo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response for the `GetServiceInfo` method: a wrapper around the
 * `ServiceInfo` snapshot. A dedicated response message (rather than
 * returning `ServiceInfo` directly) leaves room to add sibling fields
 * later without a breaking change.
 *
 * Generated from protobuf message <code>io.altessa.serviceinfo.v1.GetServiceInfoResponse</code>
 */
class GetServiceInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Runtime information for the instance handling the call.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo service_info = 1 [json_name = "serviceInfo"];</code>
     */
    protected $service_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Altessa\Serviceinfo\V1\ServiceInfo $service_info
     *           Runtime information for the instance handling the call.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Altessa\Serviceinfo\V1\ServiceinfoService::initOnce();
        parent::__construct($data);
    }

    /**
     * Runtime information for the instance handling the call.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo service_info = 1 [json_name = "serviceInfo"];</code>
     * @return \Io\Altessa\Serviceinfo\V1\ServiceInfo|null
     */
    public function getServiceInfo()
    {
        return $this->service_info;
    }

    public function hasServiceInfo()
    {
        return isset($this->service_info);
    }

    public function clearServiceInfo()
    {
        unset($this->service_info);
    }

    /**
     * Runtime information for the instance handling the call.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo service_info = 1 [json_name = "serviceInfo"];</code>
     * @param \Io\Altessa\Serviceinfo\V1\ServiceInfo $var
     * @return $this
     */
    public function setServiceInfo($var)
    {
        GPBUtil::checkMessage($var, \Io\Altessa\Serviceinfo\V1\ServiceInfo::class);
        $this->service_info = $var;

        return $this;
    }

}

