<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serviceinfo/v1/serviceinfo.proto

namespace Io\Altessa\Serviceinfo\V1;

if (false) {
    /**
     * This class is deprecated. Use Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion instead.
     * @deprecated
     */
    class ServiceInfo_SemanticVersion {}
}
class_exists(ServiceInfo\SemanticVersion::class);
@trigger_error('Io\Altessa\Serviceinfo\V1\ServiceInfo_SemanticVersion is deprecated and will be removed in the next major release. Use Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion instead', E_USER_DEPRECATED);

