<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serviceinfo/v1/serviceinfo.proto

namespace Io\Altessa\Serviceinfo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Defines detailed information about a running service instance.
 * It includes identification, versioning, build details, leadership status, and other metadata.
 *
 * Generated from protobuf message <code>io.altessa.serviceinfo.v1.ServiceInfo</code>
 */
class ServiceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The canonical name of the service (e.g., "user-service", "billing-api").
     *
     * Generated from protobuf field <code>string service_name = 1 [json_name = "serviceName"];</code>
     */
    protected $service_name = '';
    /**
     * Human-readable description of the service and its purpose.
     *
     * Generated from protobuf field <code>optional string service_description = 2 [json_name = "serviceDescription"];</code>
     */
    protected $service_description = null;
    /**
     * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *
     * Generated from protobuf field <code>optional string service_id = 3 [json_name = "serviceId"];</code>
     */
    protected $service_id = null;
    /**
     * Indicates whether this service instance is currently the leader in a distributed system.
     * True if this instance is the leader, false otherwise.
     *
     * Generated from protobuf field <code>bool is_leader = 4 [json_name = "isLeader"];</code>
     */
    protected $is_leader = false;
    /**
     * The full version string of the service (e.g., "1.2.3-alpha+build.123").
     * This may include semantic version, pre-release, and build metadata.
     *
     * Generated from protobuf field <code>string full_version = 5 [json_name = "fullVersion"];</code>
     */
    protected $full_version = '';
    /**
     * The structured semantic version of the service.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion"];</code>
     */
    protected $semantic_version = null;
    /**
     * The timestamp indicating when the service binary was built.
     * Human-readable timestamp representation (e.g., "2025-01-19T15:30:45Z").
     *
     * Generated from protobuf field <code>string build_time = 7 [json_name = "buildTime"];</code>
     */
    protected $build_time = '';
    /**
     * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *
     * Generated from protobuf field <code>optional string branch = 8 [json_name = "branch"];</code>
     */
    protected $branch = null;
    /**
     * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *
     * Generated from protobuf field <code>optional string commit = 9 [json_name = "commit"];</code>
     */
    protected $commit = null;
    /**
     * Build tags or flags used during the compilation of the service.
     *
     * Generated from protobuf field <code>optional string build_tags = 10 [json_name = "buildTags"];</code>
     */
    protected $build_tags = null;
    /**
     * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     * Keys and values are strings. Maximum 100 entries allowed.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 11 [json_name = "metadata"];</code>
     */
    private $metadata;
    /**
     * Version of the Protobuf package or definitions that this service was compiled against.
     *
     * Generated from protobuf field <code>optional string proto_version = 12 [json_name = "protoVersion"];</code>
     */
    protected $proto_version = null;
    /**
     * Identifier of the current leader instance if this node is not the leader.
     * This is useful for clients to discover the active leader.
     *
     * Generated from protobuf field <code>optional string leader_id = 13 [json_name = "leaderId"];</code>
     */
    protected $leader_id = null;
    /**
     * The timestamp when the service instance was started.
     * Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
     *
     * Generated from protobuf field <code>optional string start_time = 14 [json_name = "startTime"];</code>
     */
    protected $start_time = null;
    /**
     * The number of seconds the service has been running since startup.
     * Calculated dynamically on each request as the difference between current time and start_time.
     *
     * Generated from protobuf field <code>optional uint64 uptime = 15 [json_name = "uptime"];</code>
     */
    protected $uptime = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service_name
     *           The canonical name of the service (e.g., "user-service", "billing-api").
     *     @type string $service_description
     *           Human-readable description of the service and its purpose.
     *     @type string $service_id
     *           Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *     @type bool $is_leader
     *           Indicates whether this service instance is currently the leader in a distributed system.
     *           True if this instance is the leader, false otherwise.
     *     @type string $full_version
     *           The full version string of the service (e.g., "1.2.3-alpha+build.123").
     *           This may include semantic version, pre-release, and build metadata.
     *     @type \Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion $semantic_version
     *           The structured semantic version of the service.
     *     @type string $build_time
     *           The timestamp indicating when the service binary was built.
     *           Human-readable timestamp representation (e.g., "2025-01-19T15:30:45Z").
     *     @type string $branch
     *           Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *     @type string $commit
     *           Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *     @type string $build_tags
     *           Build tags or flags used during the compilation of the service.
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *           A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     *           Keys and values are strings. Maximum 100 entries allowed.
     *     @type string $proto_version
     *           Version of the Protobuf package or definitions that this service was compiled against.
     *     @type string $leader_id
     *           Identifier of the current leader instance if this node is not the leader.
     *           This is useful for clients to discover the active leader.
     *     @type string $start_time
     *           The timestamp when the service instance was started.
     *           Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
     *     @type int|string $uptime
     *           The number of seconds the service has been running since startup.
     *           Calculated dynamically on each request as the difference between current time and start_time.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Serviceinfo\V1\Serviceinfo::initOnce();
        parent::__construct($data);
    }

    /**
     * The canonical name of the service (e.g., "user-service", "billing-api").
     *
     * Generated from protobuf field <code>string service_name = 1 [json_name = "serviceName"];</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * The canonical name of the service (e.g., "user-service", "billing-api").
     *
     * Generated from protobuf field <code>string service_name = 1 [json_name = "serviceName"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Human-readable description of the service and its purpose.
     *
     * Generated from protobuf field <code>optional string service_description = 2 [json_name = "serviceDescription"];</code>
     * @return string
     */
    public function getServiceDescription()
    {
        return isset($this->service_description) ? $this->service_description : '';
    }

    public function hasServiceDescription()
    {
        return isset($this->service_description);
    }

    public function clearServiceDescription()
    {
        unset($this->service_description);
    }

    /**
     * Human-readable description of the service and its purpose.
     *
     * Generated from protobuf field <code>optional string service_description = 2 [json_name = "serviceDescription"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceDescription(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->service_description = $var;

        return $this;
    }

    /**
     * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *
     * Generated from protobuf field <code>optional string service_id = 3 [json_name = "serviceId"];</code>
     * @return string
     */
    public function getServiceId()
    {
        return isset($this->service_id) ? $this->service_id : '';
    }

    public function hasServiceId()
    {
        return isset($this->service_id);
    }

    public function clearServiceId()
    {
        unset($this->service_id);
    }

    /**
     * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *
     * Generated from protobuf field <code>optional string service_id = 3 [json_name = "serviceId"];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Indicates whether this service instance is currently the leader in a distributed system.
     * True if this instance is the leader, false otherwise.
     *
     * Generated from protobuf field <code>bool is_leader = 4 [json_name = "isLeader"];</code>
     * @return bool
     */
    public function getIsLeader()
    {
        return $this->is_leader;
    }

    /**
     * Indicates whether this service instance is currently the leader in a distributed system.
     * True if this instance is the leader, false otherwise.
     *
     * Generated from protobuf field <code>bool is_leader = 4 [json_name = "isLeader"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLeader(bool $var)
    {
        $this->is_leader = $var;

        return $this;
    }

    /**
     * The full version string of the service (e.g., "1.2.3-alpha+build.123").
     * This may include semantic version, pre-release, and build metadata.
     *
     * Generated from protobuf field <code>string full_version = 5 [json_name = "fullVersion"];</code>
     * @return string
     */
    public function getFullVersion()
    {
        return $this->full_version;
    }

    /**
     * The full version string of the service (e.g., "1.2.3-alpha+build.123").
     * This may include semantic version, pre-release, and build metadata.
     *
     * Generated from protobuf field <code>string full_version = 5 [json_name = "fullVersion"];</code>
     * @param string $var
     * @return $this
     */
    public function setFullVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->full_version = $var;

        return $this;
    }

    /**
     * The structured semantic version of the service.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion"];</code>
     * @return \Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion|null
     */
    public function getSemanticVersion()
    {
        return $this->semantic_version;
    }

    public function hasSemanticVersion()
    {
        return isset($this->semantic_version);
    }

    public function clearSemanticVersion()
    {
        unset($this->semantic_version);
    }

    /**
     * The structured semantic version of the service.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion"];</code>
     * @param \Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion $var
     * @return $this
     */
    public function setSemanticVersion(\Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion|null $var)
    {
        $this->semantic_version = $var;

        return $this;
    }

    /**
     * The timestamp indicating when the service binary was built.
     * Human-readable timestamp representation (e.g., "2025-01-19T15:30:45Z").
     *
     * Generated from protobuf field <code>string build_time = 7 [json_name = "buildTime"];</code>
     * @return string
     */
    public function getBuildTime()
    {
        return $this->build_time;
    }

    /**
     * The timestamp indicating when the service binary was built.
     * Human-readable timestamp representation (e.g., "2025-01-19T15:30:45Z").
     *
     * Generated from protobuf field <code>string build_time = 7 [json_name = "buildTime"];</code>
     * @param string $var
     * @return $this
     */
    public function setBuildTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->build_time = $var;

        return $this;
    }

    /**
     * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *
     * Generated from protobuf field <code>optional string branch = 8 [json_name = "branch"];</code>
     * @return string
     */
    public function getBranch()
    {
        return isset($this->branch) ? $this->branch : '';
    }

    public function hasBranch()
    {
        return isset($this->branch);
    }

    public function clearBranch()
    {
        unset($this->branch);
    }

    /**
     * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *
     * Generated from protobuf field <code>optional string branch = 8 [json_name = "branch"];</code>
     * @param string $var
     * @return $this
     */
    public function setBranch(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->branch = $var;

        return $this;
    }

    /**
     * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *
     * Generated from protobuf field <code>optional string commit = 9 [json_name = "commit"];</code>
     * @return string
     */
    public function getCommit()
    {
        return isset($this->commit) ? $this->commit : '';
    }

    public function hasCommit()
    {
        return isset($this->commit);
    }

    public function clearCommit()
    {
        unset($this->commit);
    }

    /**
     * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *
     * Generated from protobuf field <code>optional string commit = 9 [json_name = "commit"];</code>
     * @param string $var
     * @return $this
     */
    public function setCommit(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->commit = $var;

        return $this;
    }

    /**
     * Build tags or flags used during the compilation of the service.
     *
     * Generated from protobuf field <code>optional string build_tags = 10 [json_name = "buildTags"];</code>
     * @return string
     */
    public function getBuildTags()
    {
        return isset($this->build_tags) ? $this->build_tags : '';
    }

    public function hasBuildTags()
    {
        return isset($this->build_tags);
    }

    public function clearBuildTags()
    {
        unset($this->build_tags);
    }

    /**
     * Build tags or flags used during the compilation of the service.
     *
     * Generated from protobuf field <code>optional string build_tags = 10 [json_name = "buildTags"];</code>
     * @param string $var
     * @return $this
     */
    public function setBuildTags(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->build_tags = $var;

        return $this;
    }

    /**
     * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     * Keys and values are strings. Maximum 100 entries allowed.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 11 [json_name = "metadata"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     * Keys and values are strings. Maximum 100 entries allowed.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 11 [json_name = "metadata"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

    /**
     * Version of the Protobuf package or definitions that this service was compiled against.
     *
     * Generated from protobuf field <code>optional string proto_version = 12 [json_name = "protoVersion"];</code>
     * @return string
     */
    public function getProtoVersion()
    {
        return isset($this->proto_version) ? $this->proto_version : '';
    }

    public function hasProtoVersion()
    {
        return isset($this->proto_version);
    }

    public function clearProtoVersion()
    {
        unset($this->proto_version);
    }

    /**
     * Version of the Protobuf package or definitions that this service was compiled against.
     *
     * Generated from protobuf field <code>optional string proto_version = 12 [json_name = "protoVersion"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtoVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->proto_version = $var;

        return $this;
    }

    /**
     * Identifier of the current leader instance if this node is not the leader.
     * This is useful for clients to discover the active leader.
     *
     * Generated from protobuf field <code>optional string leader_id = 13 [json_name = "leaderId"];</code>
     * @return string
     */
    public function getLeaderId()
    {
        return isset($this->leader_id) ? $this->leader_id : '';
    }

    public function hasLeaderId()
    {
        return isset($this->leader_id);
    }

    public function clearLeaderId()
    {
        unset($this->leader_id);
    }

    /**
     * Identifier of the current leader instance if this node is not the leader.
     * This is useful for clients to discover the active leader.
     *
     * Generated from protobuf field <code>optional string leader_id = 13 [json_name = "leaderId"];</code>
     * @param string $var
     * @return $this
     */
    public function setLeaderId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->leader_id = $var;

        return $this;
    }

    /**
     * The timestamp when the service instance was started.
     * Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
     *
     * Generated from protobuf field <code>optional string start_time = 14 [json_name = "startTime"];</code>
     * @return string
     */
    public function getStartTime()
    {
        return isset($this->start_time) ? $this->start_time : '';
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * The timestamp when the service instance was started.
     * Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
     *
     * Generated from protobuf field <code>optional string start_time = 14 [json_name = "startTime"];</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->start_time = $var;

        return $this;
    }

    /**
     * The number of seconds the service has been running since startup.
     * Calculated dynamically on each request as the difference between current time and start_time.
     *
     * Generated from protobuf field <code>optional uint64 uptime = 15 [json_name = "uptime"];</code>
     * @return int|string
     */
    public function getUptime()
    {
        return isset($this->uptime) ? $this->uptime : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasUptime()
    {
        return isset($this->uptime);
    }

    public function clearUptime()
    {
        unset($this->uptime);
    }

    /**
     * The number of seconds the service has been running since startup.
     * Calculated dynamically on each request as the difference between current time and start_time.
     *
     * Generated from protobuf field <code>optional uint64 uptime = 15 [json_name = "uptime"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUptime(int|string $var)
    {
        GPBUtil::checkUint64($var);
        $this->uptime = $var;

        return $this;
    }

}

