<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

namespace Io\Altessa\Serviceinfo\V1;

use Spiral\RoadRunner\GRPC;

interface ServiceInfoServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "io.altessa.serviceinfo.v1.ServiceInfoService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetServiceInfoRequest $in
    * @return GetServiceInfoResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetServiceInfo(GRPC\ContextInterface $ctx, GetServiceInfoRequest $in): GetServiceInfoResponse;
}
