<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/serviceinfo/v1/serviceinfo.proto

namespace Io\Altessa\Serviceinfo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Detailed information about a running service instance: identification,
 * versioning, build details, leadership status, and arbitrary metadata.
 * Every field is populated by the server; clients MUST treat the message
 * as read-only.
 * Deployment guidance: this payload is intended for ops / diagnostic
 * use. It contains no end-user PII by design, but `metadata` MAY carry
 * environment details (region, cluster, feature flags) that you don't
 * always want exposed publicly — production deployments SHOULD gate
 * `ServiceInfoService.Get` behind authn / authz when the service is
 * not in a trusted network.
 * Snapshot semantics: `uptime` (and to a lesser extent `leader` and
 * `leader_id`) are evaluated at request time. Two consecutive calls
 * will return slightly different values; clients that need precise
 * duration arithmetic SHOULD subtract `start_time` from their own
 * clock instead of relying on `uptime`.
 *
 * Generated from protobuf message <code>io.altessa.serviceinfo.v1.ServiceInfo</code>
 */
class ServiceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * The canonical name of the service (e.g., "user-service", "billing-api").
     *
     * Generated from protobuf field <code>string service_name = 1 [json_name = "serviceName", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $service_name = '';
    /**
     * Human-readable description of the service and its purpose.
     *
     * Generated from protobuf field <code>optional string service_description = 2 [json_name = "serviceDescription", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $service_description = null;
    /**
     * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *
     * Generated from protobuf field <code>optional string service_id = 3 [json_name = "serviceId", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $service_id = null;
    /**
     * Whether this service instance is currently the leader in a distributed
     * system. True if this instance is the leader, false otherwise. (Per
     * AIP-140 boolean fields omit the `is_` prefix.)
     *
     * Generated from protobuf field <code>bool leader = 4 [json_name = "leader", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $leader = false;
    /**
     * The full version string of the service (e.g., "1.2.3-alpha+build.123").
     * This may include semantic version, pre-release, and build metadata.
     *
     * Generated from protobuf field <code>string full_version = 5 [json_name = "fullVersion", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $full_version = '';
    /**
     * The structured semantic version of the service.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $semantic_version = null;
    /**
     * Wall-clock time at which the service binary was built.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp build_time = 7 [json_name = "buildTime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $build_time = null;
    /**
     * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *
     * Generated from protobuf field <code>optional string branch = 8 [json_name = "branch", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $branch = null;
    /**
     * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *
     * Generated from protobuf field <code>optional string commit = 9 [json_name = "commit", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $commit = null;
    /**
     * Build tags or flags used during the compilation of the service.
     *
     * Generated from protobuf field <code>optional string build_tags = 10 [json_name = "buildTags", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $build_tags = null;
    /**
     * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     * Keys and values are strings. Maximum 100 entries allowed.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 11 [json_name = "metadata", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    private $metadata;
    /**
     * Identifier of the current leader instance if this node is not the leader.
     * This is useful for clients to discover the active leader.
     *
     * Generated from protobuf field <code>optional string leader_id = 13 [json_name = "leaderId", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $leader_id = null;
    /**
     * Wall-clock time at which this service instance started.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp start_time = 14 [json_name = "startTime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $start_time = null;
    /**
     * Time elapsed since `start_time`. Computed by the server on each request;
     * clients should treat it as advisory and recompute from `start_time` if
     * they need precise duration arithmetic.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Duration uptime = 15 [json_name = "uptime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $uptime = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $service_name
     *           The canonical name of the service (e.g., "user-service", "billing-api").
     *     @type string $service_description
     *           Human-readable description of the service and its purpose.
     *     @type string $service_id
     *           Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *     @type bool $leader
     *           Whether this service instance is currently the leader in a distributed
     *           system. True if this instance is the leader, false otherwise. (Per
     *           AIP-140 boolean fields omit the `is_` prefix.)
     *     @type string $full_version
     *           The full version string of the service (e.g., "1.2.3-alpha+build.123").
     *           This may include semantic version, pre-release, and build metadata.
     *     @type \Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion $semantic_version
     *           The structured semantic version of the service.
     *     @type \Google\Protobuf\Timestamp $build_time
     *           Wall-clock time at which the service binary was built.
     *     @type string $branch
     *           Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *     @type string $commit
     *           Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *     @type string $build_tags
     *           Build tags or flags used during the compilation of the service.
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *           A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     *           Keys and values are strings. Maximum 100 entries allowed.
     *     @type string $leader_id
     *           Identifier of the current leader instance if this node is not the leader.
     *           This is useful for clients to discover the active leader.
     *     @type \Google\Protobuf\Timestamp $start_time
     *           Wall-clock time at which this service instance started.
     *     @type \Google\Protobuf\Duration $uptime
     *           Time elapsed since `start_time`. Computed by the server on each request;
     *           clients should treat it as advisory and recompute from `start_time` if
     *           they need precise duration arithmetic.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Services\Serviceinfo\V1\Serviceinfo::initOnce();
        parent::__construct($data);
    }

    /**
     * The canonical name of the service (e.g., "user-service", "billing-api").
     *
     * Generated from protobuf field <code>string service_name = 1 [json_name = "serviceName", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getServiceName()
    {
        return $this->service_name;
    }

    /**
     * The canonical name of the service (e.g., "user-service", "billing-api").
     *
     * Generated from protobuf field <code>string service_name = 1 [json_name = "serviceName", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceName($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_name = $var;

        return $this;
    }

    /**
     * Human-readable description of the service and its purpose.
     *
     * Generated from protobuf field <code>optional string service_description = 2 [json_name = "serviceDescription", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getServiceDescription()
    {
        return isset($this->service_description) ? $this->service_description : '';
    }

    public function hasServiceDescription()
    {
        return isset($this->service_description);
    }

    public function clearServiceDescription()
    {
        unset($this->service_description);
    }

    /**
     * Human-readable description of the service and its purpose.
     *
     * Generated from protobuf field <code>optional string service_description = 2 [json_name = "serviceDescription", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_description = $var;

        return $this;
    }

    /**
     * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *
     * Generated from protobuf field <code>optional string service_id = 3 [json_name = "serviceId", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getServiceId()
    {
        return isset($this->service_id) ? $this->service_id : '';
    }

    public function hasServiceId()
    {
        return isset($this->service_id);
    }

    public function clearServiceId()
    {
        unset($this->service_id);
    }

    /**
     * Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
     *
     * Generated from protobuf field <code>optional string service_id = 3 [json_name = "serviceId", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setServiceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_id = $var;

        return $this;
    }

    /**
     * Whether this service instance is currently the leader in a distributed
     * system. True if this instance is the leader, false otherwise. (Per
     * AIP-140 boolean fields omit the `is_` prefix.)
     *
     * Generated from protobuf field <code>bool leader = 4 [json_name = "leader", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return bool
     */
    public function getLeader()
    {
        return $this->leader;
    }

    /**
     * Whether this service instance is currently the leader in a distributed
     * system. True if this instance is the leader, false otherwise. (Per
     * AIP-140 boolean fields omit the `is_` prefix.)
     *
     * Generated from protobuf field <code>bool leader = 4 [json_name = "leader", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param bool $var
     * @return $this
     */
    public function setLeader($var)
    {
        GPBUtil::checkBool($var);
        $this->leader = $var;

        return $this;
    }

    /**
     * The full version string of the service (e.g., "1.2.3-alpha+build.123").
     * This may include semantic version, pre-release, and build metadata.
     *
     * Generated from protobuf field <code>string full_version = 5 [json_name = "fullVersion", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getFullVersion()
    {
        return $this->full_version;
    }

    /**
     * The full version string of the service (e.g., "1.2.3-alpha+build.123").
     * This may include semantic version, pre-release, and build metadata.
     *
     * Generated from protobuf field <code>string full_version = 5 [json_name = "fullVersion", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setFullVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->full_version = $var;

        return $this;
    }

    /**
     * The structured semantic version of the service.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion|null
     */
    public function getSemanticVersion()
    {
        return $this->semantic_version;
    }

    public function hasSemanticVersion()
    {
        return isset($this->semantic_version);
    }

    public function clearSemanticVersion()
    {
        unset($this->semantic_version);
    }

    /**
     * The structured semantic version of the service.
     *
     * Generated from protobuf field <code>.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion semantic_version = 6 [json_name = "semanticVersion", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion $var
     * @return $this
     */
    public function setSemanticVersion($var)
    {
        GPBUtil::checkMessage($var, \Io\Altessa\Serviceinfo\V1\ServiceInfo\SemanticVersion::class);
        $this->semantic_version = $var;

        return $this;
    }

    /**
     * Wall-clock time at which the service binary was built.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp build_time = 7 [json_name = "buildTime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getBuildTime()
    {
        return $this->build_time;
    }

    public function hasBuildTime()
    {
        return isset($this->build_time);
    }

    public function clearBuildTime()
    {
        unset($this->build_time);
    }

    /**
     * Wall-clock time at which the service binary was built.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp build_time = 7 [json_name = "buildTime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setBuildTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->build_time = $var;

        return $this;
    }

    /**
     * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *
     * Generated from protobuf field <code>optional string branch = 8 [json_name = "branch", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getBranch()
    {
        return isset($this->branch) ? $this->branch : '';
    }

    public function hasBranch()
    {
        return isset($this->branch);
    }

    public function clearBranch()
    {
        unset($this->branch);
    }

    /**
     * Name of the source code branch from which this service instance was built (e.g., "main", "develop").
     *
     * Generated from protobuf field <code>optional string branch = 8 [json_name = "branch", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setBranch($var)
    {
        GPBUtil::checkString($var, True);
        $this->branch = $var;

        return $this;
    }

    /**
     * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *
     * Generated from protobuf field <code>optional string commit = 9 [json_name = "commit", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getCommit()
    {
        return isset($this->commit) ? $this->commit : '';
    }

    public function hasCommit()
    {
        return isset($this->commit);
    }

    public function clearCommit()
    {
        unset($this->commit);
    }

    /**
     * Full Git commit hash (SHA) of the source code revision from which this service instance was built.
     *
     * Generated from protobuf field <code>optional string commit = 9 [json_name = "commit", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setCommit($var)
    {
        GPBUtil::checkString($var, True);
        $this->commit = $var;

        return $this;
    }

    /**
     * Build tags or flags used during the compilation of the service.
     *
     * Generated from protobuf field <code>optional string build_tags = 10 [json_name = "buildTags", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getBuildTags()
    {
        return isset($this->build_tags) ? $this->build_tags : '';
    }

    public function hasBuildTags()
    {
        return isset($this->build_tags);
    }

    public function clearBuildTags()
    {
        unset($this->build_tags);
    }

    /**
     * Build tags or flags used during the compilation of the service.
     *
     * Generated from protobuf field <code>optional string build_tags = 10 [json_name = "buildTags", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setBuildTags($var)
    {
        GPBUtil::checkString($var, True);
        $this->build_tags = $var;

        return $this;
    }

    /**
     * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     * Keys and values are strings. Maximum 100 entries allowed.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 11 [json_name = "metadata", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * A collection of key-value pairs for additional, arbitrary metadata about the service instance.
     * Keys and values are strings. Maximum 100 entries allowed.
     *
     * Generated from protobuf field <code>map<string, string> metadata = 11 [json_name = "metadata", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

    /**
     * Identifier of the current leader instance if this node is not the leader.
     * This is useful for clients to discover the active leader.
     *
     * Generated from protobuf field <code>optional string leader_id = 13 [json_name = "leaderId", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getLeaderId()
    {
        return isset($this->leader_id) ? $this->leader_id : '';
    }

    public function hasLeaderId()
    {
        return isset($this->leader_id);
    }

    public function clearLeaderId()
    {
        unset($this->leader_id);
    }

    /**
     * Identifier of the current leader instance if this node is not the leader.
     * This is useful for clients to discover the active leader.
     *
     * Generated from protobuf field <code>optional string leader_id = 13 [json_name = "leaderId", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setLeaderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->leader_id = $var;

        return $this;
    }

    /**
     * Wall-clock time at which this service instance started.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp start_time = 14 [json_name = "startTime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    public function hasStartTime()
    {
        return isset($this->start_time);
    }

    public function clearStartTime()
    {
        unset($this->start_time);
    }

    /**
     * Wall-clock time at which this service instance started.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Timestamp start_time = 14 [json_name = "startTime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Time elapsed since `start_time`. Computed by the server on each request;
     * clients should treat it as advisory and recompute from `start_time` if
     * they need precise duration arithmetic.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Duration uptime = 15 [json_name = "uptime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getUptime()
    {
        return $this->uptime;
    }

    public function hasUptime()
    {
        return isset($this->uptime);
    }

    public function clearUptime()
    {
        unset($this->uptime);
    }

    /**
     * Time elapsed since `start_time`. Computed by the server on each request;
     * clients should treat it as advisory and recompute from `start_time` if
     * they need precise duration arithmetic.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Duration uptime = 15 [json_name = "uptime", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setUptime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->uptime = $var;

        return $this;
    }

}

