<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: serviceinfo/v1/serviceinfo_service.proto

namespace Io\Altessa\Serviceinfo\V1;

use Spiral\GRPC;
use Google\Protobuf;

interface ServiceInfoServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "io.altessa.serviceinfo.v1.ServiceInfoService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Protobuf\GPBEmpty $in
    * @return ServiceInfo
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Get(GRPC\ContextInterface $ctx, Protobuf\GPBEmpty $in): ServiceInfo;
}
