<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serviceinfo/v1/serviceinfo_service.proto

namespace GPBMetadata\Serviceinfo\V1;

class ServiceinfoService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Serviceinfo\V1\Serviceinfo::initOnce();
        $pool->internalAddGeneratedFile(
            '
«
(serviceinfo/v1/serviceinfo_service.protoio.altessa.serviceinfo.v1 serviceinfo/v1/serviceinfo.proto2[
ServiceInfoServiceE
Get.google.protobuf.Empty&.io.altessa.serviceinfo.v1.ServiceInfoB]
io.altessa.serviceinfo.v1PZ>github.com/altessa-s/proto-gen-go/serviceinfo/v1;serviceinfov1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

