<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serviceinfo/v1/serviceinfo_service.proto

namespace GPBMetadata\Serviceinfo\V1;

class ServiceinfoService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Serviceinfo\V1\Serviceinfo::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAB\x02\x0A(serviceinfo/v1/serviceinfo_service.proto\x12\x19io.altessa.serviceinfo.v1\x1A serviceinfo/v1/serviceinfo.proto2[\x0A\x12ServiceInfoService\x12E\x0A\x03Get\x12\x16.google.protobuf.Empty\x1A&.io.altessa.serviceinfo.v1.ServiceInfoB]\x0A\x19io.altessa.serviceinfo.v1P\x01Z>github.com/altessa-s/proto-gen-go/serviceinfo/v1;serviceinfov1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

