<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/color.proto

namespace GPBMetadata\Google\Type;

class Color
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(
            '
…
google/type/color.protogoogle.type"v
Color
red (Rred
green (Rgreen
blue (Rblue1
alpha (2.google.protobuf.FloatValueRalphaB]
com.google.typeB
ColorProtoPZ6google.golang.org/genproto/googleapis/type/color;color¢GTPbproto3'
        , true);

        static::$is_initialized = true;
    }
}

