<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/type/date.proto

namespace GPBMetadata\Google\Type;

class Date
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Í
google/type/date.protogoogle.type"B
Date
year (Ryear
month (Rmonth
day (RdayBZ
com.google.typeB	DateProtoPZ4google.golang.org/genproto/googleapis/type/date;date¢GTPbproto3'
        , true);

        static::$is_initialized = true;
    }
}

