<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

namespace GPBMetadata\Io\Altessa\Serviceinfo\V1;

class ServiceinfoService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Io\Altessa\Serviceinfo\V1\Serviceinfo::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ë
3io/altessa/serviceinfo/v1/serviceinfo_service.protoio.altessa.serviceinfo.v1"
GetServiceInfoRequest"c
GetServiceInfoResponseI
service_info (2&.io.altessa.serviceinfo.v1.ServiceInfoRserviceInfo2ã
ServiceInfoServiceu
GetServiceInfo0.io.altessa.serviceinfo.v1.GetServiceInfoRequest1.io.altessa.serviceinfo.v1.GetServiceInfoResponseBÅ
io.altessa.serviceinfo.v1BServiceInfoServiceProtoPZIgithub.com/altessa-s/proto-gen-go/io/altessa/serviceinfo/v1;serviceinfov1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

