<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serviceinfo/v1/serviceinfo.proto

namespace Io\Altessa\Serviceinfo\V1\ServiceInfo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Defines a version conforming to the Semantic Versioning 2.0.0 specification (semver.org).
 *
 * Generated from protobuf message <code>io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion</code>
 */
class SemanticVersion extends \Google\Protobuf\Internal\Message
{
    /**
     * The MAJOR version, incremented for incompatible API changes.
     *
     * Generated from protobuf field <code>uint32 major = 1 [json_name = "major"];</code>
     */
    protected $major = 0;
    /**
     * The MINOR version, incremented for adding functionality in a backward-compatible manner.
     *
     * Generated from protobuf field <code>uint32 minor = 2 [json_name = "minor"];</code>
     */
    protected $minor = 0;
    /**
     * The PATCH version, incremented for backward-compatible bug fixes.
     *
     * Generated from protobuf field <code>uint32 patch = 3 [json_name = "patch"];</code>
     */
    protected $patch = 0;
    /**
     * Pre-release identifier (e.g., "alpha", "beta.1").
     * A series of dot-separated identifiers immediately following the patch version.
     *
     * Generated from protobuf field <code>optional string pre_release = 4 [json_name = "preRelease"];</code>
     */
    protected $pre_release = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $major
     *           The MAJOR version, incremented for incompatible API changes.
     *     @type int $minor
     *           The MINOR version, incremented for adding functionality in a backward-compatible manner.
     *     @type int $patch
     *           The PATCH version, incremented for backward-compatible bug fixes.
     *     @type string $pre_release
     *           Pre-release identifier (e.g., "alpha", "beta.1").
     *           A series of dot-separated identifiers immediately following the patch version.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Serviceinfo\V1\Serviceinfo::initOnce();
        parent::__construct($data);
    }

    /**
     * The MAJOR version, incremented for incompatible API changes.
     *
     * Generated from protobuf field <code>uint32 major = 1 [json_name = "major"];</code>
     * @return int
     */
    public function getMajor()
    {
        return $this->major;
    }

    /**
     * The MAJOR version, incremented for incompatible API changes.
     *
     * Generated from protobuf field <code>uint32 major = 1 [json_name = "major"];</code>
     * @param int $var
     * @return $this
     */
    public function setMajor(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->major = $var;

        return $this;
    }

    /**
     * The MINOR version, incremented for adding functionality in a backward-compatible manner.
     *
     * Generated from protobuf field <code>uint32 minor = 2 [json_name = "minor"];</code>
     * @return int
     */
    public function getMinor()
    {
        return $this->minor;
    }

    /**
     * The MINOR version, incremented for adding functionality in a backward-compatible manner.
     *
     * Generated from protobuf field <code>uint32 minor = 2 [json_name = "minor"];</code>
     * @param int $var
     * @return $this
     */
    public function setMinor(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->minor = $var;

        return $this;
    }

    /**
     * The PATCH version, incremented for backward-compatible bug fixes.
     *
     * Generated from protobuf field <code>uint32 patch = 3 [json_name = "patch"];</code>
     * @return int
     */
    public function getPatch()
    {
        return $this->patch;
    }

    /**
     * The PATCH version, incremented for backward-compatible bug fixes.
     *
     * Generated from protobuf field <code>uint32 patch = 3 [json_name = "patch"];</code>
     * @param int $var
     * @return $this
     */
    public function setPatch(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->patch = $var;

        return $this;
    }

    /**
     * Pre-release identifier (e.g., "alpha", "beta.1").
     * A series of dot-separated identifiers immediately following the patch version.
     *
     * Generated from protobuf field <code>optional string pre_release = 4 [json_name = "preRelease"];</code>
     * @return string
     */
    public function getPreRelease()
    {
        return isset($this->pre_release) ? $this->pre_release : '';
    }

    public function hasPreRelease()
    {
        return isset($this->pre_release);
    }

    public function clearPreRelease()
    {
        unset($this->pre_release);
    }

    /**
     * Pre-release identifier (e.g., "alpha", "beta.1").
     * A series of dot-separated identifiers immediately following the patch version.
     *
     * Generated from protobuf field <code>optional string pre_release = 4 [json_name = "preRelease"];</code>
     * @param string $var
     * @return $this
     */
    public function setPreRelease(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->pre_release = $var;

        return $this;
    }

}

