<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/date_period.proto

namespace GPBMetadata\Io\Altessa\Type\V1;

class DatePeriod
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Type\Date::initOnce();
        $pool->internalAddGeneratedFile(
            '
∏
$io/altessa/type/v1/date_period.protoio.altessa.type.v1google/type/date.proto"v

DatePeriod5

start_date (2.google.type.DateB‡AR	startDate1
end_date (2.google.type.DateB‡ARendDateBd
io.altessa.type.v1BDatePeriodProtoPZ;github.com/altessa-s/proto-gen-go/io/altessa/type/v1;typev1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

