<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/label.proto

namespace GPBMetadata\Io\Altessa\Type\V1;

class Label
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Type\Color::initOnce();
        $pool->internalAddGeneratedFile(
            '
ô
io/altessa/type/v1/label.protoio.altessa.type.v1google/type/color.proto"a
Label
id (	B‡ARid
value (	B‡ARvalue(
color (2.google.type.ColorRcolorB_
io.altessa.type.v1B
LabelProtoPZ;github.com/altessa-s/proto-gen-go/io/altessa/type/v1;typev1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

