<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/money_range.proto

namespace GPBMetadata\Io\Altessa\Type\V1;

class MoneyRange
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Type\Money::initOnce();
        $pool->internalAddGeneratedFile(
            '
•
$io/altessa/type/v1/money_range.protoio.altessa.type.v1google/type/money.proto"b

MoneyRange)
min (2.google.type.MoneyB‡ARmin)
max (2.google.type.MoneyB‡ARmaxBd
io.altessa.type.v1BMoneyRangeProtoPZ;github.com/altessa-s/proto-gen-go/io/altessa/type/v1;typev1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

