<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/contact.proto

namespace Io\Altessa\Type\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A single contact endpoint (phone, email, social handle, …). The variant
 * of `value` carries both the payload and the category — consumers
 * dispatch on the oneof case instead of inspecting a separate type tag.
 * Phone numbers use google.type.PhoneNumber so country code and extension
 * are preserved structurally; email and social handles are opaque strings
 * whose format is not enforced by this schema.
 *
 * Generated from protobuf message <code>io.altessa.type.v1.Contact</code>
 */
class Contact extends \Google\Protobuf\Internal\Message
{
    /**
     * Stable identifier of the contact within its issuing system. Opaque to
     * consumers; used to address this contact in per-element operations on
     * parent messages (e.g. updating one entry in a `repeated Contact` list
     * without replacing the whole list). Assigned at creation and never
     * changes afterwards — to "rename" a contact, delete and recreate it.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $id = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Stable identifier of the contact within its issuing system. Opaque to
     *           consumers; used to address this contact in per-element operations on
     *           parent messages (e.g. updating one entry in a `repeated Contact` list
     *           without replacing the whole list). Assigned at creation and never
     *           changes afterwards — to "rename" a contact, delete and recreate it.
     *     @type string $email
     *           Email address.
     *     @type \Google\Type\PhoneNumber $phone
     *           Telephone number with structured country code, extension, and
     *           short-code support.
     *     @type string $social_handle
     *           Social media handle (e.g. "&#64;alice" on a network identified
     *           out-of-band).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Type\V1\Contact::initOnce();
        parent::__construct($data);
    }

    /**
     * Stable identifier of the contact within its issuing system. Opaque to
     * consumers; used to address this contact in per-element operations on
     * parent messages (e.g. updating one entry in a `repeated Contact` list
     * without replacing the whole list). Assigned at creation and never
     * changes afterwards — to "rename" a contact, delete and recreate it.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Stable identifier of the contact within its issuing system. Opaque to
     * consumers; used to address this contact in per-element operations on
     * parent messages (e.g. updating one entry in a `repeated Contact` list
     * without replacing the whole list). Assigned at creation and never
     * changes afterwards — to "rename" a contact, delete and recreate it.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Email address.
     *
     * Generated from protobuf field <code>string email = 2 [json_name = "email"];</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->readOneof(2);
    }

    public function hasEmail()
    {
        return $this->hasOneof(2);
    }

    /**
     * Email address.
     *
     * Generated from protobuf field <code>string email = 2 [json_name = "email"];</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Telephone number with structured country code, extension, and
     * short-code support.
     *
     * Generated from protobuf field <code>.google.type.PhoneNumber phone = 3 [json_name = "phone"];</code>
     * @return \Google\Type\PhoneNumber|null
     */
    public function getPhone()
    {
        return $this->readOneof(3);
    }

    public function hasPhone()
    {
        return $this->hasOneof(3);
    }

    /**
     * Telephone number with structured country code, extension, and
     * short-code support.
     *
     * Generated from protobuf field <code>.google.type.PhoneNumber phone = 3 [json_name = "phone"];</code>
     * @param \Google\Type\PhoneNumber $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\PhoneNumber::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Social media handle (e.g. "&#64;alice" on a network identified
     * out-of-band).
     *
     * Generated from protobuf field <code>string social_handle = 4 [json_name = "socialHandle"];</code>
     * @return string
     */
    public function getSocialHandle()
    {
        return $this->readOneof(4);
    }

    public function hasSocialHandle()
    {
        return $this->hasOneof(4);
    }

    /**
     * Social media handle (e.g. "&#64;alice" on a network identified
     * out-of-band).
     *
     * Generated from protobuf field <code>string social_handle = 4 [json_name = "socialHandle"];</code>
     * @param string $var
     * @return $this
     */
    public function setSocialHandle($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

