<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/date_period.proto

namespace Io\Altessa\Type\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A calendar-date range, inclusive on both ends. Use this for ranges that
 * have no wall-clock component (billing periods, leave windows, …);
 * use google.type.Interval for ranges defined by absolute timestamps.
 * Producers MUST ensure `end_date >= start_date`. A zero-length period
 * (start == end) is a valid one-day range. Consumers SHOULD reject
 * requests that violate the ordering invariant with INVALID_ARGUMENT.
 * `google.type.Date` permits partially-specified values (year-only,
 * year + month, …). `DatePeriod` requires BOTH bounds to be fully
 * specified — non-zero `year`, `month`, and `day` — so consumers can
 * do calendar arithmetic without ambiguity. Producers SHOULD reject
 * partial dates before constructing a `DatePeriod`.
 * Timezone: `google.type.Date` is timezone-naive by design. The
 * surrounding domain decides how to interpret it (e.g. "the billing
 * month in the merchant's local tz"). Do not attach timezone state to
 * a `DatePeriod` via a side-channel — if you need timezone-aware
 * ranges, use `google.type.Interval` instead.
 *
 * Generated from protobuf message <code>io.altessa.type.v1.DatePeriod</code>
 */
class DatePeriod extends \Google\Protobuf\Internal\Message
{
    /**
     * Start date, inclusive.
     *
     * Generated from protobuf field <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $start_date = null;
    /**
     * End date, inclusive. MUST be on or after start_date.
     *
     * Generated from protobuf field <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $end_date = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Type\Date $start_date
     *           Start date, inclusive.
     *     @type \Google\Type\Date $end_date
     *           End date, inclusive. MUST be on or after start_date.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Altessa\Type\V1\DatePeriod::initOnce();
        parent::__construct($data);
    }

    /**
     * Start date, inclusive.
     *
     * Generated from protobuf field <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Type\Date|null
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    public function hasStartDate()
    {
        return isset($this->start_date);
    }

    public function clearStartDate()
    {
        unset($this->start_date);
    }

    /**
     * Start date, inclusive.
     *
     * Generated from protobuf field <code>.google.type.Date start_date = 1 [json_name = "startDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @param \Google\Type\Date $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\Date::class);
        $this->start_date = $var;

        return $this;
    }

    /**
     * End date, inclusive. MUST be on or after start_date.
     *
     * Generated from protobuf field <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Type\Date|null
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    public function hasEndDate()
    {
        return isset($this->end_date);
    }

    public function clearEndDate()
    {
        unset($this->end_date);
    }

    /**
     * End date, inclusive. MUST be on or after start_date.
     *
     * Generated from protobuf field <code>.google.type.Date end_date = 2 [json_name = "endDate", (.google.api.field_behavior) = REQUIRED];</code>
     * @param \Google\Type\Date $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\Date::class);
        $this->end_date = $var;

        return $this;
    }

}

