<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/document_ref.proto

namespace Io\Altessa\Type\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A user-facing document: a FileRef plus presentation metadata. Use this
 * when displaying attached documents in UIs ("Contract.pdf — signed copy");
 * use FileRef directly when only the underlying file is needed.
 *
 * Generated from protobuf message <code>io.altessa.type.v1.DocumentRef</code>
 */
class DocumentRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Underlying file.
     *
     * Generated from protobuf field <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $file = null;
    /**
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     *
     * Generated from protobuf field <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $title = '';
    /**
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     *
     * Generated from protobuf field <code>optional string description = 3 [json_name = "description"];</code>
     */
    protected $description = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Altessa\Type\V1\FileRef $file
     *           Underlying file.
     *     @type string $title
     *           Display title, e.g. "Service agreement — 2026 edition". Not required
     *           to match `file.metadata.filename`.
     *     @type string $description
     *           Longer-form description shown alongside the title (purpose, version
     *           notes, …).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Altessa\Type\V1\DocumentRef::initOnce();
        parent::__construct($data);
    }

    /**
     * Underlying file.
     *
     * Generated from protobuf field <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     * @return \Io\Altessa\Type\V1\FileRef|null
     */
    public function getFile()
    {
        return $this->file;
    }

    public function hasFile()
    {
        return isset($this->file);
    }

    public function clearFile()
    {
        unset($this->file);
    }

    /**
     * Underlying file.
     *
     * Generated from protobuf field <code>.io.altessa.type.v1.FileRef file = 1 [json_name = "file", (.google.api.field_behavior) = REQUIRED];</code>
     * @param \Io\Altessa\Type\V1\FileRef $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkMessage($var, \Io\Altessa\Type\V1\FileRef::class);
        $this->file = $var;

        return $this;
    }

    /**
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     *
     * Generated from protobuf field <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Display title, e.g. "Service agreement — 2026 edition". Not required
     * to match `file.metadata.filename`.
     *
     * Generated from protobuf field <code>string title = 2 [json_name = "title", (.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     *
     * Generated from protobuf field <code>optional string description = 3 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->description) ? $this->description : '';
    }

    public function hasDescription()
    {
        return isset($this->description);
    }

    public function clearDescription()
    {
        unset($this->description);
    }

    /**
     * Longer-form description shown alongside the title (purpose, version
     * notes, …).
     *
     * Generated from protobuf field <code>optional string description = 3 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

}

