<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/file_ref.proto

namespace Io\Altessa\Type\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Reference to a file held in an external system (object storage, CDN, …).
 * Carries enough information to retrieve the file and describe it for
 * display. The schema is intentionally storage-agnostic — neither bucket
 * nor backend is encoded here.
 *
 * Generated from protobuf message <code>io.altessa.type.v1.FileRef</code>
 */
class FileRef extends \Google\Protobuf\Internal\Message
{
    /**
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     *
     * Generated from protobuf field <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $url = '';
    /**
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     *
     * Generated from protobuf field <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $id = '';
    /**
     * File metadata, when known.
     *
     * Generated from protobuf field <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     */
    protected $metadata = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *           URL for accessing the file. MAY be permanent or a time-limited signed
     *           URL — readers must not cache it beyond the lifetime granted by the
     *           issuer.
     *     @type string $id
     *           Stable identifier of the file in the issuing system. Opaque to
     *           consumers; suitable for re-requesting a fresh URL. Assigned at
     *           upload time and never changes afterwards.
     *     @type \Io\Altessa\Type\V1\FileRef\Metadata $metadata
     *           File metadata, when known.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Type\V1\FileRef::initOnce();
        parent::__construct($data);
    }

    /**
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     *
     * Generated from protobuf field <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * URL for accessing the file. MAY be permanent or a time-limited signed
     * URL — readers must not cache it beyond the lifetime granted by the
     * issuer.
     *
     * Generated from protobuf field <code>string url = 1 [json_name = "url", (.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     *
     * Generated from protobuf field <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Stable identifier of the file in the issuing system. Opaque to
     * consumers; suitable for re-requesting a fresh URL. Assigned at
     * upload time and never changes afterwards.
     *
     * Generated from protobuf field <code>string id = 2 [json_name = "id", (.google.api.field_behavior) = REQUIRED, (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * File metadata, when known.
     *
     * Generated from protobuf field <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     * @return \Io\Altessa\Type\V1\FileRef\Metadata|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * File metadata, when known.
     *
     * Generated from protobuf field <code>.io.altessa.type.v1.FileRef.Metadata metadata = 3 [json_name = "metadata"];</code>
     * @param \Io\Altessa\Type\V1\FileRef\Metadata $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Io\Altessa\Type\V1\FileRef\Metadata::class);
        $this->metadata = $var;

        return $this;
    }

}

