<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/file_ref.proto

namespace Io\Altessa\Type\V1;

if (false) {
    /**
     * This class is deprecated. Use Io\Altessa\Type\V1\FileRef\Metadata instead.
     * @deprecated
     */
    class FileRef_Metadata {}
}
class_exists(FileRef\Metadata::class);
@trigger_error('Io\Altessa\Type\V1\FileRef_Metadata is deprecated and will be removed in the next major release. Use Io\Altessa\Type\V1\FileRef\Metadata instead', E_USER_DEPRECATED);

