<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/gender.proto

namespace Io\Altessa\Type\V1;

use UnexpectedValueException;

/**
 * Biological sex of a person. Intentionally minimal — extend the schema in
 * downstream code if richer gender identity is needed (this enum stays
 * stable and small so it can be reused across unrelated services).
 * Stability (AIP-180): closed and frozen at v1. New values are NOT
 * expected; consumers MAY assume the value set will not grow.
 *
 * Protobuf type <code>io.altessa.type.v1.Gender</code>
 */
class Gender
{
    /**
     * Sentinel default. Treat as "not provided" rather than as a value.
     *
     * Generated from protobuf enum <code>GENDER_UNSPECIFIED = 0;</code>
     */
    const GENDER_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>GENDER_MALE = 1;</code>
     */
    const GENDER_MALE = 1;
    /**
     * Generated from protobuf enum <code>GENDER_FEMALE = 2;</code>
     */
    const GENDER_FEMALE = 2;

    private static $valueToName = [
        self::GENDER_UNSPECIFIED => 'GENDER_UNSPECIFIED',
        self::GENDER_MALE => 'GENDER_MALE',
        self::GENDER_FEMALE => 'GENDER_FEMALE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

