<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/label.proto

namespace Io\Altessa\Type\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A short text tag with an optional display color. Suitable for chips,
 * badges, and other UI affordances where a stable id is needed alongside
 * the rendered text.
 * Scope: `id` is unique within the issuing system, not globally — when
 * embedding `Label` from multiple systems in one client, namespace by
 * source rather than assuming id uniqueness across them.
 * Localization: `value` is a single string in a single language.
 * Consumers that need multi-language rendering SHOULD localize at the
 * boundary (e.g. via a translation map keyed by `id`) rather than
 * shipping multiple `Label` instances per language.
 *
 * Generated from protobuf message <code>io.altessa.type.v1.Label</code>
 */
class Label extends \Google\Protobuf\Internal\Message
{
    /**
     * Stable identifier of the label within its issuing system. Opaque to
     * consumers. Assigned at creation and never changes afterwards.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     */
    protected $id = '';
    /**
     * Display text, e.g. "Urgent", "Завершено".
     *
     * Generated from protobuf field <code>string value = 2 [json_name = "value", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $value = '';
    /**
     * Display color. When unset, consumers SHOULD fall back to a neutral
     * default.
     *
     * Generated from protobuf field <code>.google.type.Color color = 3 [json_name = "color"];</code>
     */
    protected $color = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Stable identifier of the label within its issuing system. Opaque to
     *           consumers. Assigned at creation and never changes afterwards.
     *     @type string $value
     *           Display text, e.g. "Urgent", "Завершено".
     *     @type \Google\Type\Color $color
     *           Display color. When unset, consumers SHOULD fall back to a neutral
     *           default.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Io\Altessa\Type\V1\Label::initOnce();
        parent::__construct($data);
    }

    /**
     * Stable identifier of the label within its issuing system. Opaque to
     * consumers. Assigned at creation and never changes afterwards.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Stable identifier of the label within its issuing system. Opaque to
     * consumers. Assigned at creation and never changes afterwards.
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id", (.google.api.field_behavior) = IDENTIFIER];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Display text, e.g. "Urgent", "Завершено".
     *
     * Generated from protobuf field <code>string value = 2 [json_name = "value", (.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Display text, e.g. "Urgent", "Завершено".
     *
     * Generated from protobuf field <code>string value = 2 [json_name = "value", (.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Display color. When unset, consumers SHOULD fall back to a neutral
     * default.
     *
     * Generated from protobuf field <code>.google.type.Color color = 3 [json_name = "color"];</code>
     * @return \Google\Type\Color|null
     */
    public function getColor()
    {
        return $this->color;
    }

    public function hasColor()
    {
        return isset($this->color);
    }

    public function clearColor()
    {
        unset($this->color);
    }

    /**
     * Display color. When unset, consumers SHOULD fall back to a neutral
     * default.
     *
     * Generated from protobuf field <code>.google.type.Color color = 3 [json_name = "color"];</code>
     * @param \Google\Type\Color $var
     * @return $this
     */
    public function setColor($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\Color::class);
        $this->color = $var;

        return $this;
    }

}

