<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/location_privacy.proto

namespace Io\Altessa\Type\V1;

use UnexpectedValueException;

/**
 * Privacy level applied to a user's geolocation before it is exposed to
 * other users or downstream services. The actor that holds raw coordinates
 * is expected to coarsen them according to this enum before propagation.
 * The schema only mandates the precision tier — the exact coarsening
 * method (truncation, round-to-nearest, geohash, k-anonymity bucket,
 * …) is the producer's choice. Producers SHOULD pick one method and
 * apply it deterministically per user, so the user's exposed position
 * does not jitter between requests with no real-world movement (this
 * would otherwise leak the true position via averaging).
 * Stability (AIP-180): closed and frozen at v1. New values are NOT
 * expected; new precision tiers belong in domain-specific schemas
 * rather than as additions here.
 *
 * Protobuf type <code>io.altessa.type.v1.LocationPrivacy</code>
 */
class LocationPrivacy
{
    /**
     * Sentinel default. When received from a client in a request, servers
     * SHOULD reject with INVALID_ARGUMENT so the privacy choice is
     * explicit. When read from persistent storage, servers SHOULD apply
     * the most restrictive interpretation (= treat as LOCATION_PRIVACY_OFF).
     *
     * Generated from protobuf enum <code>LOCATION_PRIVACY_UNSPECIFIED = 0;</code>
     */
    const LOCATION_PRIVACY_UNSPECIFIED = 0;
    /**
     * Tracking disabled. Coordinates must not be persisted.
     *
     * Generated from protobuf enum <code>LOCATION_PRIVACY_OFF = 1;</code>
     */
    const LOCATION_PRIVACY_OFF = 1;
    /**
     * Coordinates are persisted but not exposed to other users. The owner can
     * search relative to their own position; they remain non-discoverable to
     * peers.
     *
     * Generated from protobuf enum <code>LOCATION_PRIVACY_PRIVATE = 2;</code>
     */
    const LOCATION_PRIVACY_PRIVATE = 2;
    /**
     * City-scale precision: coordinates rounded to ~10 km (≈ 0.1°).
     *
     * Generated from protobuf enum <code>LOCATION_PRIVACY_PUBLIC_CITY = 3;</code>
     */
    const LOCATION_PRIVACY_PUBLIC_CITY = 3;
    /**
     * Neighbourhood-scale precision: coordinates rounded to ~1 km (≈ 0.01°).
     *
     * Generated from protobuf enum <code>LOCATION_PRIVACY_PUBLIC_APPROXIMATE = 4;</code>
     */
    const LOCATION_PRIVACY_PUBLIC_APPROXIMATE = 4;
    /**
     * Full precision (~10 m). Coordinates are exposed as captured.
     *
     * Generated from protobuf enum <code>LOCATION_PRIVACY_PUBLIC_EXACT = 5;</code>
     */
    const LOCATION_PRIVACY_PUBLIC_EXACT = 5;

    private static $valueToName = [
        self::LOCATION_PRIVACY_UNSPECIFIED => 'LOCATION_PRIVACY_UNSPECIFIED',
        self::LOCATION_PRIVACY_OFF => 'LOCATION_PRIVACY_OFF',
        self::LOCATION_PRIVACY_PRIVATE => 'LOCATION_PRIVACY_PRIVATE',
        self::LOCATION_PRIVACY_PUBLIC_CITY => 'LOCATION_PRIVACY_PUBLIC_CITY',
        self::LOCATION_PRIVACY_PUBLIC_APPROXIMATE => 'LOCATION_PRIVACY_PUBLIC_APPROXIMATE',
        self::LOCATION_PRIVACY_PUBLIC_EXACT => 'LOCATION_PRIVACY_PUBLIC_EXACT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

