<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/money_range.proto

namespace Io\Altessa\Type\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Inclusive range between two monetary amounts. Both bounds MUST share
 * the same `currency_code` and `min` MUST NOT exceed `max`; producers
 * are responsible for enforcing both invariants. A zero-length range
 * (`min == max`) is valid and represents a single amount.
 * `MoneyRange` has no notion of open or half-open ranges — both bounds
 * are required. For one-sided thresholds ("amounts above $100",
 * "amounts up to $1000"), use a single `google.type.Money` on the
 * surrounding message instead of synthesising a sentinel `min` / `max`.
 * Negative amounts are permitted (credits, refunds, signed P&L). The
 * ordering invariant still applies: `min <= max` as signed values
 * (e.g. min = -100, max = -10 is well-formed; min = -10, max = -100 is
 * not).
 *
 * Generated from protobuf message <code>io.altessa.type.v1.MoneyRange</code>
 */
class MoneyRange extends \Google\Protobuf\Internal\Message
{
    /**
     * Lower bound, inclusive.
     *
     * Generated from protobuf field <code>.google.type.Money min = 1 [json_name = "min", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $min = null;
    /**
     * Upper bound, inclusive. MUST be in the same currency as `min` and
     * greater than or equal to `min`.
     *
     * Generated from protobuf field <code>.google.type.Money max = 2 [json_name = "max", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $max = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Type\Money $min
     *           Lower bound, inclusive.
     *     @type \Google\Type\Money $max
     *           Upper bound, inclusive. MUST be in the same currency as `min` and
     *           greater than or equal to `min`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Type\V1\MoneyRange::initOnce();
        parent::__construct($data);
    }

    /**
     * Lower bound, inclusive.
     *
     * Generated from protobuf field <code>.google.type.Money min = 1 [json_name = "min", (.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Type\Money|null
     */
    public function getMin()
    {
        return $this->min;
    }

    public function hasMin()
    {
        return isset($this->min);
    }

    public function clearMin()
    {
        unset($this->min);
    }

    /**
     * Lower bound, inclusive.
     *
     * Generated from protobuf field <code>.google.type.Money min = 1 [json_name = "min", (.google.api.field_behavior) = REQUIRED];</code>
     * @param \Google\Type\Money $var
     * @return $this
     */
    public function setMin($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\Money::class);
        $this->min = $var;

        return $this;
    }

    /**
     * Upper bound, inclusive. MUST be in the same currency as `min` and
     * greater than or equal to `min`.
     *
     * Generated from protobuf field <code>.google.type.Money max = 2 [json_name = "max", (.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Type\Money|null
     */
    public function getMax()
    {
        return $this->max;
    }

    public function hasMax()
    {
        return isset($this->max);
    }

    public function clearMax()
    {
        unset($this->max);
    }

    /**
     * Upper bound, inclusive. MUST be in the same currency as `min` and
     * greater than or equal to `min`.
     *
     * Generated from protobuf field <code>.google.type.Money max = 2 [json_name = "max", (.google.api.field_behavior) = REQUIRED];</code>
     * @param \Google\Type\Money $var
     * @return $this
     */
    public function setMax($var)
    {
        GPBUtil::checkMessage($var, \Google\Type\Money::class);
        $this->max = $var;

        return $this;
    }

}

