<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/organization_type.proto

namespace Io\Altessa\Type\V1;

use UnexpectedValueException;

/**
 * Legal form of an organization at a coarse level. Use this when the
 * distinction "natural person doing business" vs "registered legal entity"
 * is enough; jurisdiction-specific subtypes (ИП vs самозанятый, LLC vs
 * C-corp, …) belong in a domain-specific schema.
 * Stability (AIP-180): closed and frozen at v1. New values are NOT
 * expected; jurisdiction-specific subtypes are added in domain
 * schemas, not here.
 *
 * Protobuf type <code>io.altessa.type.v1.OrganizationType</code>
 */
class OrganizationType
{
    /**
     * Sentinel default. Treat as "not provided" rather than as a value.
     *
     * Generated from protobuf enum <code>ORGANIZATION_TYPE_UNSPECIFIED = 0;</code>
     */
    const ORGANIZATION_TYPE_UNSPECIFIED = 0;
    /**
     * Natural person operating as a sole proprietor / individual entrepreneur
     * (e.g. ИП in RU, sole trader in UK, sole proprietorship in US).
     *
     * Generated from protobuf enum <code>ORGANIZATION_TYPE_INDIVIDUAL = 1;</code>
     */
    const ORGANIZATION_TYPE_INDIVIDUAL = 1;
    /**
     * Registered legal entity distinct from its owners (e.g. ООО / АО in RU,
     * LLC / Inc. in US, GmbH / AG in DE).
     *
     * Generated from protobuf enum <code>ORGANIZATION_TYPE_ORGANIZATION = 2;</code>
     */
    const ORGANIZATION_TYPE_ORGANIZATION = 2;

    private static $valueToName = [
        self::ORGANIZATION_TYPE_UNSPECIFIED => 'ORGANIZATION_TYPE_UNSPECIFIED',
        self::ORGANIZATION_TYPE_INDIVIDUAL => 'ORGANIZATION_TYPE_INDIVIDUAL',
        self::ORGANIZATION_TYPE_ORGANIZATION => 'ORGANIZATION_TYPE_ORGANIZATION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

