<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/pagination.proto

namespace Io\Altessa\Type\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Pagination parameters for list requests. Field names and types follow
 * https://google.aip.dev/158; the message additionally carries an
 * `offset` field for collections where token-based continuation is
 * inconvenient (small, slow-changing, or admin-only lists).
 * `page_token` and `offset` are mutually exclusive — set at most one.
 * Request-side only. This message covers the parameters a client sends;
 * services define their own list-response shape — by convention a
 * repeated items field at position 1 plus a `string next_page_token`
 * that callers feed back into `page_token` on the following request.
 * There is intentionally no shared `PaginationResponse` here because
 * the items-field type and optional total counts vary per service.
 * `page_size` semantics: zero requests the service-defined default of
 * 1000 items. Servers MUST cap it at an implementation-defined maximum
 * and MUST return INVALID_ARGUMENT for negative values. The
 * NON_EMPTY_DEFAULT annotation signals that the server substitutes a
 * concrete non-empty value (1000) when the client leaves the field
 * unset.
 * `page_token` semantics: opaque string minted by the server. Clients
 * MUST round-trip it verbatim and MUST NOT decode or synthesise one.
 * Servers MAY invalidate tokens at any time (schema migrations,
 * snapshot expiry) and SHOULD respond with INVALID_ARGUMENT or a typed
 * error rather than silently restarting from the first page.
 * `offset` semantics: number of items to skip from the start of the
 * unpaginated result set. Prefer `page_token` for large or rapidly
 * changing collections — `offset` re-scans the result set and is
 * subject to drift when items are inserted or deleted between calls.
 *
 * Generated from protobuf message <code>io.altessa.type.v1.Pagination</code>
 */
class Pagination extends \Google\Protobuf\Internal\Message
{
    /**
     * Maximum number of items the server should return. Zero requests
     * the service-defined default (1000); negative values yield
     * INVALID_ARGUMENT.
     *
     * Generated from protobuf field <code>int32 page_size = 1 [json_name = "pageSize", (.google.api.field_behavior) = NON_EMPTY_DEFAULT];</code>
     */
    protected $page_size = 0;
    /**
     * Opaque continuation token returned in a previous list response.
     * Empty (the default) requests the first page. Mutually exclusive
     * with `offset`.
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     */
    protected $page_token = '';
    /**
     * Number of items to skip from the start of the unpaginated result
     * set. Zero (the proto3 default) requests the first page. Mutually
     * exclusive with `page_token`.
     *
     * Generated from protobuf field <code>int32 offset = 3 [json_name = "offset"];</code>
     */
    protected $offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $page_size
     *           Maximum number of items the server should return. Zero requests
     *           the service-defined default (1000); negative values yield
     *           INVALID_ARGUMENT.
     *     @type string $page_token
     *           Opaque continuation token returned in a previous list response.
     *           Empty (the default) requests the first page. Mutually exclusive
     *           with `offset`.
     *     @type int $offset
     *           Number of items to skip from the start of the unpaginated result
     *           set. Zero (the proto3 default) requests the first page. Mutually
     *           exclusive with `page_token`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Type\V1\Pagination::initOnce();
        parent::__construct($data);
    }

    /**
     * Maximum number of items the server should return. Zero requests
     * the service-defined default (1000); negative values yield
     * INVALID_ARGUMENT.
     *
     * Generated from protobuf field <code>int32 page_size = 1 [json_name = "pageSize", (.google.api.field_behavior) = NON_EMPTY_DEFAULT];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Maximum number of items the server should return. Zero requests
     * the service-defined default (1000); negative values yield
     * INVALID_ARGUMENT.
     *
     * Generated from protobuf field <code>int32 page_size = 1 [json_name = "pageSize", (.google.api.field_behavior) = NON_EMPTY_DEFAULT];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Opaque continuation token returned in a previous list response.
     * Empty (the default) requests the first page. Mutually exclusive
     * with `offset`.
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Opaque continuation token returned in a previous list response.
     * Empty (the default) requests the first page. Mutually exclusive
     * with `offset`.
     *
     * Generated from protobuf field <code>string page_token = 2 [json_name = "pageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * Number of items to skip from the start of the unpaginated result
     * set. Zero (the proto3 default) requests the first page. Mutually
     * exclusive with `page_token`.
     *
     * Generated from protobuf field <code>int32 offset = 3 [json_name = "offset"];</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Number of items to skip from the start of the unpaginated result
     * set. Zero (the proto3 default) requests the first page. Mutually
     * exclusive with `page_token`.
     *
     * Generated from protobuf field <code>int32 offset = 3 [json_name = "offset"];</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->offset = $var;

        return $this;
    }

}

