<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/sort_direction.proto

namespace Io\Altessa\Type\V1;

use UnexpectedValueException;

/**
 * Ordering direction for list / search responses. Typically appears in
 * a list request next to a service-specific sort-field selector, e.g.
 *   message ListUsersRequest {
 *     string sort_by = 1;             // service-defined field name
 *     SortDirection direction = 2;
 *     Pagination pagination = 3;
 *   }
 * For multi-key ordering or per-field direction, services define their
 * own richer sort message — this enum stays a single-direction
 * primitive on purpose.
 * Zero value: unlike most enums in this package, `SortDirection` does
 * not have an `_UNSPECIFIED` zero value. `SORT_DIRECTION_ASC = 0` is
 * the natural default (matches SQL `ORDER BY` without `DESC`), so a
 * distinct sentinel would add noise without information. This is the
 * only exception in `type/v1` (see `buf.yaml` for the lint waiver).
 * Stability (AIP-180): closed and frozen at v1. There are only two
 * meaningful directions for a single sort key; consumers MAY assume
 * the value set will not grow.
 *
 * Protobuf type <code>io.altessa.type.v1.SortDirection</code>
 */
class SortDirection
{
    /**
     * Ascending: A→Z, 0→9, oldest first. This is the default.
     *
     * Generated from protobuf enum <code>SORT_DIRECTION_ASC = 0;</code>
     */
    const SORT_DIRECTION_ASC = 0;
    /**
     * Descending: Z→A, 9→0, newest first.
     *
     * Generated from protobuf enum <code>SORT_DIRECTION_DESC = 1;</code>
     */
    const SORT_DIRECTION_DESC = 1;

    private static $valueToName = [
        self::SORT_DIRECTION_ASC => 'SORT_DIRECTION_ASC',
        self::SORT_DIRECTION_DESC => 'SORT_DIRECTION_DESC',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

