<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/file_ref.proto

namespace GPBMetadata\Type\V1;

class FileRef
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        $pool->internalAddGeneratedFile(
            '
Â
type/v1/file_ref.protoio.altessa.type.v1"‰
FileRef
url (	B‡ARurl
id (	B‡A‡ARid@
metadata (2$.io.altessa.type.v1.FileRef.MetadataRmetadataÁ
Metadata
	mime_type (	RmimeType

size_bytes (R	sizeBytes
filename (	RfilenameH
custom (20.io.altessa.type.v1.FileRef.Metadata.CustomEntryRcustom9
CustomEntry
key (	Rkey
value (	Rvalue:8BH
io.altessa.type.v1PZ0github.com/altessa-s/proto-gen-go/type/v1;typev1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

