<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/label.proto

namespace GPBMetadata\Type\V1;

class Label
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Type\Color::initOnce();
        $pool->internalAddGeneratedFile(
            '
˙
type/v1/label.protoio.altessa.type.v1google/type/color.proto"d
Label
id (	B‡A‡ARid
value (	B‡ARvalue(
color (2.google.type.ColorRcolorBH
io.altessa.type.v1PZ0github.com/altessa-s/proto-gen-go/type/v1;typev1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

