<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type/v1/pagination.proto

namespace GPBMetadata\Type\V1;

class Pagination
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        $pool->internalAddGeneratedFile(
            '
Á
type/v1/pagination.protoio.altessa.type.v1"e

Pagination 
	page_size (B‡ARpageSize

page_token (	R	pageToken
offset (RoffsetBH
io.altessa.type.v1PZ0github.com/altessa-s/proto-gen-go/type/v1;typev1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

