<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badrequest/v1/badrequest.proto

namespace Io\Altessa\Badrequest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines a general error structure for requests that are malformed or contain invalid data.
 * It typically includes a list of specific field violations that caused the request to be rejected.
 * This message is often used as a detail payload for `google.rpc.Status` when the error code is `INVALID_ARGUMENT`.
 *
 * Generated from protobuf message <code>io.altessa.badrequest.v1.BadRequest</code>
 */
class BadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of individual field violations that contributed to the bad request.
     *
     * Generated from protobuf field <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     */
    private $field_violations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Io\Altessa\Badrequest\V1\FieldViolation>|\Google\Protobuf\Internal\RepeatedField $field_violations
     *           A list of individual field violations that contributed to the bad request.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Badrequest\V1\Badrequest::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of individual field violations that contributed to the bad request.
     *
     * Generated from protobuf field <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldViolations()
    {
        return $this->field_violations;
    }

    /**
     * A list of individual field violations that contributed to the bad request.
     *
     * Generated from protobuf field <code>repeated .io.altessa.badrequest.v1.FieldViolation field_violations = 1 [json_name = "fieldViolations"];</code>
     * @param array<\Io\Altessa\Badrequest\V1\FieldViolation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldViolations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Altessa\Badrequest\V1\FieldViolation::class);
        $this->field_violations = $arr;

        return $this;
    }

}

