<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badrequest/v1/badrequest.proto

namespace Io\Altessa\Badrequest\V1;

use UnexpectedValueException;

/**
 * FieldType mirrors google.protobuf.FieldDescriptorProto.Type as an open
 * proto3 enum so this schema is usable from PHP and other generators
 * that disallow proto2 closed-enum dependencies in proto3 files. Numeric
 * values intentionally match the upstream FieldDescriptorProto.Type so
 * tools can cast or round-trip without a lookup table.
 *
 * Protobuf type <code>io.altessa.badrequest.v1.FieldType</code>
 */
class FieldType
{
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_UNSPECIFIED = 0;</code>
     */
    const FIELD_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_DOUBLE = 1;</code>
     */
    const FIELD_TYPE_DOUBLE = 1;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_FLOAT = 2;</code>
     */
    const FIELD_TYPE_FLOAT = 2;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_INT64 = 3;</code>
     */
    const FIELD_TYPE_INT64 = 3;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_UINT64 = 4;</code>
     */
    const FIELD_TYPE_UINT64 = 4;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_INT32 = 5;</code>
     */
    const FIELD_TYPE_INT32 = 5;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_FIXED64 = 6;</code>
     */
    const FIELD_TYPE_FIXED64 = 6;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_FIXED32 = 7;</code>
     */
    const FIELD_TYPE_FIXED32 = 7;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_BOOL = 8;</code>
     */
    const FIELD_TYPE_BOOL = 8;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_STRING = 9;</code>
     */
    const FIELD_TYPE_STRING = 9;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_GROUP = 10;</code>
     */
    const FIELD_TYPE_GROUP = 10;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_MESSAGE = 11;</code>
     */
    const FIELD_TYPE_MESSAGE = 11;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_BYTES = 12;</code>
     */
    const FIELD_TYPE_BYTES = 12;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_UINT32 = 13;</code>
     */
    const FIELD_TYPE_UINT32 = 13;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_ENUM = 14;</code>
     */
    const FIELD_TYPE_ENUM = 14;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_SFIXED32 = 15;</code>
     */
    const FIELD_TYPE_SFIXED32 = 15;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_SFIXED64 = 16;</code>
     */
    const FIELD_TYPE_SFIXED64 = 16;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_SINT32 = 17;</code>
     */
    const FIELD_TYPE_SINT32 = 17;
    /**
     * Generated from protobuf enum <code>FIELD_TYPE_SINT64 = 18;</code>
     */
    const FIELD_TYPE_SINT64 = 18;

    private static $valueToName = [
        self::FIELD_TYPE_UNSPECIFIED => 'FIELD_TYPE_UNSPECIFIED',
        self::FIELD_TYPE_DOUBLE => 'FIELD_TYPE_DOUBLE',
        self::FIELD_TYPE_FLOAT => 'FIELD_TYPE_FLOAT',
        self::FIELD_TYPE_INT64 => 'FIELD_TYPE_INT64',
        self::FIELD_TYPE_UINT64 => 'FIELD_TYPE_UINT64',
        self::FIELD_TYPE_INT32 => 'FIELD_TYPE_INT32',
        self::FIELD_TYPE_FIXED64 => 'FIELD_TYPE_FIXED64',
        self::FIELD_TYPE_FIXED32 => 'FIELD_TYPE_FIXED32',
        self::FIELD_TYPE_BOOL => 'FIELD_TYPE_BOOL',
        self::FIELD_TYPE_STRING => 'FIELD_TYPE_STRING',
        self::FIELD_TYPE_GROUP => 'FIELD_TYPE_GROUP',
        self::FIELD_TYPE_MESSAGE => 'FIELD_TYPE_MESSAGE',
        self::FIELD_TYPE_BYTES => 'FIELD_TYPE_BYTES',
        self::FIELD_TYPE_UINT32 => 'FIELD_TYPE_UINT32',
        self::FIELD_TYPE_ENUM => 'FIELD_TYPE_ENUM',
        self::FIELD_TYPE_SFIXED32 => 'FIELD_TYPE_SFIXED32',
        self::FIELD_TYPE_SFIXED64 => 'FIELD_TYPE_SFIXED64',
        self::FIELD_TYPE_SINT32 => 'FIELD_TYPE_SINT32',
        self::FIELD_TYPE_SINT64 => 'FIELD_TYPE_SINT64',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

