<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badrequest/v1/badrequest.proto

namespace Io\Altessa\Badrequest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines a single segment in the path to a violated field.
 * It provides details about the field name, number, type, and, if applicable, its index in a repeated field or its key in a map.
 *
 * Generated from protobuf message <code>io.altessa.badrequest.v1.FieldPathComponent</code>
 */
class FieldPathComponent extends \Google\Protobuf\Internal\Message
{
    /**
     * Field number as defined in the .proto file.
     *
     * Generated from protobuf field <code>optional int32 number = 1 [json_name = "number"];</code>
     */
    protected $number = null;
    /**
     * Name of the field as defined in the .proto file.
     *
     * Generated from protobuf field <code>optional string name = 2 [json_name = "name"];</code>
     */
    protected $name = null;
    /**
     * Data type of the field.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type"];</code>
     */
    protected $type = null;
    /**
     * For map fields, specifies the data type of the map keys.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType"];</code>
     */
    protected $map_key_type = null;
    /**
     * For map fields, specifies the data type of the map values.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType"];</code>
     */
    protected $map_value_type = null;
    /**
     * Indicates whether the field is a repeated field (i.e., an array or list).
     *
     * Generated from protobuf field <code>optional bool is_repeated = 6 [json_name = "isRepeated"];</code>
     */
    protected $is_repeated = null;
    /**
     * For repeated fields, the 0-based index of the element that caused the violation.
     *
     * Generated from protobuf field <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex"];</code>
     */
    protected $repeated_index = null;
    protected $map_key;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $number
     *           Field number as defined in the .proto file.
     *     @type string $name
     *           Name of the field as defined in the .proto file.
     *     @type int $type
     *           Data type of the field.
     *     @type int $map_key_type
     *           For map fields, specifies the data type of the map keys.
     *     @type int $map_value_type
     *           For map fields, specifies the data type of the map values.
     *     @type bool $is_repeated
     *           Indicates whether the field is a repeated field (i.e., an array or list).
     *     @type int|string $repeated_index
     *           For repeated fields, the 0-based index of the element that caused the violation.
     *     @type int|string $index
     *           The index if the map key is treated as an array index (less common for proto maps).
     *     @type bool $bool_key
     *           The map key, if its type is `bool`.
     *     @type int|string $int_key
     *           The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
     *     @type int|string $uint_key
     *           The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
     *     @type string $string_key
     *           The map key, if its type is `string`.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Badrequest\V1\Badrequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Field number as defined in the .proto file.
     *
     * Generated from protobuf field <code>optional int32 number = 1 [json_name = "number"];</code>
     * @return int
     */
    public function getNumber()
    {
        return isset($this->number) ? $this->number : 0;
    }

    public function hasNumber()
    {
        return isset($this->number);
    }

    public function clearNumber()
    {
        unset($this->number);
    }

    /**
     * Field number as defined in the .proto file.
     *
     * Generated from protobuf field <code>optional int32 number = 1 [json_name = "number"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->number = $var;

        return $this;
    }

    /**
     * Name of the field as defined in the .proto file.
     *
     * Generated from protobuf field <code>optional string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Name of the field as defined in the .proto file.
     *
     * Generated from protobuf field <code>optional string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Data type of the field.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type"];</code>
     * @return int
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : 0;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Data type of the field.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType type = 3 [json_name = "type"];</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Io\Altessa\Badrequest\V1\FieldType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * For map fields, specifies the data type of the map keys.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType"];</code>
     * @return int
     */
    public function getMapKeyType()
    {
        return isset($this->map_key_type) ? $this->map_key_type : 0;
    }

    public function hasMapKeyType()
    {
        return isset($this->map_key_type);
    }

    public function clearMapKeyType()
    {
        unset($this->map_key_type);
    }

    /**
     * For map fields, specifies the data type of the map keys.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType map_key_type = 4 [json_name = "mapKeyType"];</code>
     * @param int $var
     * @return $this
     */
    public function setMapKeyType($var)
    {
        GPBUtil::checkEnum($var, \Io\Altessa\Badrequest\V1\FieldType::class);
        $this->map_key_type = $var;

        return $this;
    }

    /**
     * For map fields, specifies the data type of the map values.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType"];</code>
     * @return int
     */
    public function getMapValueType()
    {
        return isset($this->map_value_type) ? $this->map_value_type : 0;
    }

    public function hasMapValueType()
    {
        return isset($this->map_value_type);
    }

    public function clearMapValueType()
    {
        unset($this->map_value_type);
    }

    /**
     * For map fields, specifies the data type of the map values.
     *
     * Generated from protobuf field <code>optional .io.altessa.badrequest.v1.FieldType map_value_type = 5 [json_name = "mapValueType"];</code>
     * @param int $var
     * @return $this
     */
    public function setMapValueType($var)
    {
        GPBUtil::checkEnum($var, \Io\Altessa\Badrequest\V1\FieldType::class);
        $this->map_value_type = $var;

        return $this;
    }

    /**
     * Indicates whether the field is a repeated field (i.e., an array or list).
     *
     * Generated from protobuf field <code>optional bool is_repeated = 6 [json_name = "isRepeated"];</code>
     * @return bool
     */
    public function getIsRepeated()
    {
        return isset($this->is_repeated) ? $this->is_repeated : false;
    }

    public function hasIsRepeated()
    {
        return isset($this->is_repeated);
    }

    public function clearIsRepeated()
    {
        unset($this->is_repeated);
    }

    /**
     * Indicates whether the field is a repeated field (i.e., an array or list).
     *
     * Generated from protobuf field <code>optional bool is_repeated = 6 [json_name = "isRepeated"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRepeated($var)
    {
        GPBUtil::checkBool($var);
        $this->is_repeated = $var;

        return $this;
    }

    /**
     * For repeated fields, the 0-based index of the element that caused the violation.
     *
     * Generated from protobuf field <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex"];</code>
     * @return int|string
     */
    public function getRepeatedIndex()
    {
        return isset($this->repeated_index) ? $this->repeated_index : 0;
    }

    public function hasRepeatedIndex()
    {
        return isset($this->repeated_index);
    }

    public function clearRepeatedIndex()
    {
        unset($this->repeated_index);
    }

    /**
     * For repeated fields, the 0-based index of the element that caused the violation.
     *
     * Generated from protobuf field <code>optional uint64 repeated_index = 7 [json_name = "repeatedIndex"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRepeatedIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->repeated_index = $var;

        return $this;
    }

    /**
     * The index if the map key is treated as an array index (less common for proto maps).
     *
     * Generated from protobuf field <code>uint64 index = 8 [json_name = "index"];</code>
     * @return int|string
     */
    public function getIndex()
    {
        return $this->readOneof(8);
    }

    public function hasIndex()
    {
        return $this->hasOneof(8);
    }

    /**
     * The index if the map key is treated as an array index (less common for proto maps).
     *
     * Generated from protobuf field <code>uint64 index = 8 [json_name = "index"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * The map key, if its type is `bool`.
     *
     * Generated from protobuf field <code>bool bool_key = 9 [json_name = "boolKey"];</code>
     * @return bool
     */
    public function getBoolKey()
    {
        return $this->readOneof(9);
    }

    public function hasBoolKey()
    {
        return $this->hasOneof(9);
    }

    /**
     * The map key, if its type is `bool`.
     *
     * Generated from protobuf field <code>bool bool_key = 9 [json_name = "boolKey"];</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolKey($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
     *
     * Generated from protobuf field <code>int64 int_key = 10 [json_name = "intKey"];</code>
     * @return int|string
     */
    public function getIntKey()
    {
        return $this->readOneof(10);
    }

    public function hasIntKey()
    {
        return $this->hasOneof(10);
    }

    /**
     * The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
     *
     * Generated from protobuf field <code>int64 int_key = 10 [json_name = "intKey"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntKey($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
     *
     * Generated from protobuf field <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
     * @return int|string
     */
    public function getUintKey()
    {
        return $this->readOneof(11);
    }

    public function hasUintKey()
    {
        return $this->hasOneof(11);
    }

    /**
     * The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
     *
     * Generated from protobuf field <code>uint64 uint_key = 11 [json_name = "uintKey"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUintKey($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * The map key, if its type is `string`.
     *
     * Generated from protobuf field <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @return string
     */
    public function getStringKey()
    {
        return $this->readOneof(12);
    }

    public function hasStringKey()
    {
        return $this->hasOneof(12);
    }

    /**
     * The map key, if its type is `string`.
     *
     * Generated from protobuf field <code>string string_key = 12 [json_name = "stringKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setStringKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMapKey()
    {
        return $this->whichOneof("map_key");
    }

}

