<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badrequest/v1/badrequest.proto

namespace Io\Altessa\Badrequest\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines a specific issue with a single field in the request message.
 * It provides details about which field was problematic and why.
 *
 * Generated from protobuf message <code>io.altessa.badrequest.v1.FieldViolation</code>
 */
class FieldViolation extends \Google\Protobuf\Internal\Message
{
    /**
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     *
     * Generated from protobuf field <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     */
    protected $field_path = null;
    /**
     * Human-readable message describing the violation.
     *
     * Generated from protobuf field <code>optional string message = 2 [json_name = "message"];</code>
     */
    protected $message = null;
    /**
     * Application-specific error code or identifier for this type of violation.
     *
     * Generated from protobuf field <code>optional string code = 3 [json_name = "code"];</code>
     */
    protected $code = null;
    /**
     * Structured representation of the path to the field that caused the violation.
     *
     * Generated from protobuf field <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     */
    private $field_path_components;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $field_path
     *           The dot-separated path to the field that caused the violation.
     *           For example, "user.address.street" or "items[2].name".
     *     @type string $message
     *           Human-readable message describing the violation.
     *     @type string $code
     *           Application-specific error code or identifier for this type of violation.
     *     @type array<\Io\Altessa\Badrequest\V1\FieldPathComponent>|\Google\Protobuf\Internal\RepeatedField $field_path_components
     *           Structured representation of the path to the field that caused the violation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Badrequest\V1\Badrequest::initOnce();
        parent::__construct($data);
    }

    /**
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     *
     * Generated from protobuf field <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @return string
     */
    public function getFieldPath()
    {
        return isset($this->field_path) ? $this->field_path : '';
    }

    public function hasFieldPath()
    {
        return isset($this->field_path);
    }

    public function clearFieldPath()
    {
        unset($this->field_path);
    }

    /**
     * The dot-separated path to the field that caused the violation.
     * For example, "user.address.street" or "items[2].name".
     *
     * Generated from protobuf field <code>optional string field_path = 1 [json_name = "fieldPath"];</code>
     * @param string $var
     * @return $this
     */
    public function setFieldPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->field_path = $var;

        return $this;
    }

    /**
     * Human-readable message describing the violation.
     *
     * Generated from protobuf field <code>optional string message = 2 [json_name = "message"];</code>
     * @return string
     */
    public function getMessage()
    {
        return isset($this->message) ? $this->message : '';
    }

    public function hasMessage()
    {
        return isset($this->message);
    }

    public function clearMessage()
    {
        unset($this->message);
    }

    /**
     * Human-readable message describing the violation.
     *
     * Generated from protobuf field <code>optional string message = 2 [json_name = "message"];</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Application-specific error code or identifier for this type of violation.
     *
     * Generated from protobuf field <code>optional string code = 3 [json_name = "code"];</code>
     * @return string
     */
    public function getCode()
    {
        return isset($this->code) ? $this->code : '';
    }

    public function hasCode()
    {
        return isset($this->code);
    }

    public function clearCode()
    {
        unset($this->code);
    }

    /**
     * Application-specific error code or identifier for this type of violation.
     *
     * Generated from protobuf field <code>optional string code = 3 [json_name = "code"];</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Structured representation of the path to the field that caused the violation.
     *
     * Generated from protobuf field <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFieldPathComponents()
    {
        return $this->field_path_components;
    }

    /**
     * Structured representation of the path to the field that caused the violation.
     *
     * Generated from protobuf field <code>repeated .io.altessa.badrequest.v1.FieldPathComponent field_path_components = 4 [json_name = "fieldPathComponents"];</code>
     * @param array<\Io\Altessa\Badrequest\V1\FieldPathComponent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFieldPathComponents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Altessa\Badrequest\V1\FieldPathComponent::class);
        $this->field_path_components = $arr;

        return $this;
    }

}

