<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/serviceinfo/v1/serviceinfo_service.proto

namespace GPBMetadata\Services\Serviceinfo\V1;

class ServiceinfoService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Services\Serviceinfo\V1\Serviceinfo::initOnce();
        $pool->internalAddGeneratedFile(
            '
Æ
1services/serviceinfo/v1/serviceinfo_service.protoio.altessa.serviceinfo.v1)services/serviceinfo/v1/serviceinfo.proto2[
ServiceInfoServiceE
Get.google.protobuf.Empty&.io.altessa.serviceinfo.v1.ServiceInfoBf
io.altessa.serviceinfo.v1PZGgithub.com/altessa-s/proto-gen-go/services/serviceinfo/v1;serviceinfov1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

